In [40]:
import numpy as np

def create_matrix(rowsize, columnsize):
  matrix = []

  for i in range(rowsize):
    row = []

    for j in range(columnsize):
      try:
        nums = int(input(f"Enter the value at index ({i}, {j}) (one at a time): "))
        row.append(nums)
      except:
        return

    matrix.append(row)

  return np.array(matrix)

def SVD_function(matrix):
  U, S, Vtranspose = np.linalg.svd(matrix)
  return U, S, Vtranspose

def main():
  rowsize = int(input('Enter the Row size: '))
  columnsize = int(input('Enter the Column size: '))

  matrix = create_matrix(rowsize, columnsize)

  if matrix is None:
    print('Invalid input at an index')
    return

  print("\nInputted Matrix: ")
  print(matrix)
  print("\n")

  U, S, Vtranspose = SVD_function(matrix)
  print("Matrix U :")
  print(U)
  print("\n")

  print("Matrix Σ :")
  S_final = np.zeros((matrix.shape[0], matrix.shape[1]))
  np.fill_diagonal(S_final, S)
  print(S_final)
  print("\n")

  print("Vᵀ (Right Singular Vectors):")
  print(Vtranspose)
  print("\n")

  print("Result check: ")
  result_check = U @ S_final @ Vtranspose
  print(result_check)

main()

Enter the Row size: 2
Enter the Column size: 3
Enter the value at index (0, 0) (one at a time): 1
Enter the value at index (0, 1) (one at a time): -1
Enter the value at index (0, 2) (one at a time): 3
Enter the value at index (1, 0) (one at a time): 3
Enter the value at index (1, 1) (one at a time): 1
Enter the value at index (1, 2) (one at a time): 1

Inputted Matrix: 
[[ 1 -1  3]
 [ 3  1  1]]


Matrix U :
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


Matrix Σ :
[[4.         0.         0.        ]
 [0.         2.44948974 0.        ]]


Vᵀ (Right Singular Vectors):
[[-7.07106781e-01  1.20868191e-16 -7.07106781e-01]
 [ 5.77350269e-01  5.77350269e-01 -5.77350269e-01]
 [-4.08248290e-01  8.16496581e-01  4.08248290e-01]]


Result check: 
[[ 1. -1.  3.]
 [ 3.  1.  1.]]
